name: 'minutemedia-kaniko'
description: 'Build docker image with Kaniko'
inputs:
  username:
    description: "Username used for authentication to the Docker registry"
    required: true
  password:
    description: "Password used for authentication to the Docker registry"
    required: true
  image:
    description: "Image name"
    required: true
  tag:
    description: "Image tag"
    required: true
  build_file:
    description: "Dockerfile filename"
    required: false
runs:
  using: "composite"
  steps:
    - run: ${{ github.action_path }}/kaniko.sh
      shell: bash