name: 'minutemedia-kaniko'
description: 'Build docker image with Kaniko'
inputs:
  commit:
    description: 'github commit sha'
    required: true
runs:
  using: "composite"
  steps:
    - run: ${{ github.action_path }}/kaniko.sh
      shell: bash
      env:
        commit: ${{ inputs.commit }}