name: 'minutemedia-kaniko'
description: 'Build docker image with Kaniko'
inputs:
  username:
    description: "Username used for authentication to the Docker registry"
    required: true
  password:
    description: "Password used for authentication to the Docker registry"
    required: true
  image:
    description: "Image name"
    required: true
  tag:
    description: "Image tag"
    required: true
  context:
    description: "build context"
    required: true
  dockerfile:
    description: "Dockerfile filename"
    required: true
runs:
  using: "composite"
  steps:
    - run: ${{ github.action_path }}/kaniko.sh
      shell: bash
      env:
        username: ${{ inputs.username }}
        password: ${{ inputs.password }}
        image: ${{ inputs.image }}
        tag: ${{ inputs.tag }}
        dockerfile: ${{ inputs.dockerfile }}
        context: ${{ inputs.context }}