name: 'minutemedia-kaniko'
description: 'Build docker image with Kaniko'
inputs:
  username:
    description: "Username used for authentication to the Docker registry"
    required: true
  password:
    description: "Password used for authentication to the Docker registry"
    required: true
  image:
    description: "Image name"
    required: true
  tag:
    description: "Image tag"
    required: true
  build_file:
    description: "Dockerfile filename"
    required: true
  dockerfile:
    description: "Dockerfile filename"
    required: true
  github_token:
    description: "github token"
    required: true
  branch:
    description: "github branch"
    required: true
runs:
  using: "composite"
  steps:
    - run: ${{ github.action_path }}/kaniko.sh
      shell: bash
      env:
        username: ${{ inputs.username }}
        build_file: ${{ inputs.build_file }}
        password: ${{ inputs.password }}
        image: ${{ inputs.image }}
        tag: ${{ inputs.tag }}
        dockerfile: ${{ inputs.dockerfile }}
        github_token: ${{ inputs.github_token }}
        branch: ${{ inputs.branch }}